### PR TITLE
Fix deprecated syntax and use of Pkg.dir in the tests

### PR DESCRIPTION
**Pull request by yuyichao**
(Also some white space)

### CODE REVIEW

**Comment by yuyichao** [comment]
The only remaining depwarn in the test run is https://github.com/JuliaStats/Distributions.jl/pull/431

**Comment by yuyichao** [comment]
I updated the travis settings to use `language: julia` which should be a much more relable/newer version. I also disabled `Compose` checkout because `he really shouldnt be checking out master of compose if he wants tests to be release representative` -- Tony. Is there a good reason the test is running against Compose master (e.g. are you always releasing the two at the same time)?

**Comment by yuyichao** [comment]
Note that the nightly test is expected to fail but it should be fixed by https://github.com/dcjones/Compose.jl/pull/164 .

**Comment by yuyichao** [comment]
I put the checkout back since it looks like the two are meant to be in sync.

**Comment by dcjones** [comment]
Thanks! They are meant to be in sync, I basically always tag them simultaneously.

**Pull request merged**
