### PR TITLE
Typo in error handling code

### PR DESCRIPTION
**Pull request by joehuchette**
Without this, I was getting a really cryptic error message in ``sortperm!``.

### CODE REVIEW

**Comment by joehuchette** [comment]
@dcjones this is failing the ``stat_qq.jl`` test with a call like
```jl
x = rand(Normal(), 100)
pl9 = plot(x=x, y=Normal(), color=rand(length(x)), Stat.qq, Geom.point)
```
When Gadfly is applying the ``QQStatistic``, it rewrites ``x`` and ``y`` to the output of ``Distributions.qqbuild``, which strips off two entries, leaving ``length(x) == length(y) == 98`` but ``color`` unchanged with ``length(color) == 100``. Any idea how to fix this?

**Comment by joehuchette** [comment]
(Note that without this fix, ``assert_aesthetics_equal_length`` would never produce an error)

**Comment by dcjones** [comment]
Thanks for fixing this. I'm thinking that I'll just disallow `color` with `Stat.qq`. I don't know of anything reasonable to do with it if `Stat.qq` is not 1-1.

**Comment by joehuchette** [comment]
Seems reasonable. I looked into that, but couldn't figure out the right mechanism to disallow certain combinations of things like that.

**Pull request merged**
