### PR TITLE
WIP: transitioning docs to Documenter.jl

### LINKED ISSUE #852: Theme documentation outdated
The `Theme` documentation on the Gadfly web site, which I assume is produced from docs/themes.md, refers to the field `highlight_color`, which no longer exists. It has been replaced by `discrete_highlight_color` and `continuous_highlight_color`.

### PR DESCRIPTION
**Pull request by tlnagy**
Working on #878. This fixes #852, #865, and probably many others.

screen shot 2016-08-22 at 23 10 40

Couple things left

- [x] Fix regressions in `src/lib/guide_manual_color_key.md`
- [x] in `src/man/plotting.md`
- [x] Get plotting working https://github.com/JuliaDocs/Documenter.jl/issues/229
- [x] Set up Travis to auto-generate documentation for stable and release versions of Gadfly
- [ ] Too many items in navbar https://github.com/JuliaDocs/Documenter.jl/issues/230
- [x] Add Author information back in
- [x] Update README
- [x] replace lots of #hide statements with `@setup` blocks JuliaDocs/Documenter.jl#244
- [x] Fix Theme documentation #852 
- [x] Add Mattriks' new geometry

### CODE REVIEW

**Comment by tlnagy** [comment]
@rsrock, @shashi, @timholy I would appreciate any thoughts/comments!

**Comment by Hydrotoast** [comment]
Which theme are you using here? This appears to be slightly different from the `readthedocs` theme.

**Comment by tlnagy** [comment]
It is the default theme for the HTML output of Documenter.jl (I'm not
using MkDocs).


On Tue, Aug 23, 2016, at 21:39, Gio Borje wrote:
> Which theme are you using here? This appears to be slightly different
> from the readthedocs theme.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
>

Links:

  1. https://github.com/dcjones/Gadfly.jl/pull/879#issuecomment-241955432

**Comment by tlnagy** [comment]
@shashi Do you have access to the travis keys for this project. It would be awesome to set up CI to autogenerate the docs and have the latest/stable versions. See https://juliadocs.github.io/Documenter.jl/latest/man/hosting.html#Deploy-Keys-1

**Comment by rsrock** [comment]
Is there any way to look at this live?  Can you set it up on your fork?

**Comment by tlnagy** [comment]
I'll see what I can do

**Comment by tlnagy** [comment]
I'll build it locally and push it to my `gh-pages` branch, but it's crashing right now due to bugs in `Gadfly`, specifically waiting for my fix at #884 to get merged. I'll let you know once I have a live version up and running.

**Comment by tlnagy** [comment]
@rsrock Here's a live demo: http://tamasnagy.com/Gadfly.jl/

**Comment by rsrock** [comment]
Man, this is nice.  I'd like it if this was merged as soon as you're ready.  Great work!

**Comment by tlnagy** [comment]
Thanks! 🎉 

I'm waiting for https://github.com/dcjones/Gadfly.jl/pull/885 to merge and then all the docs can be built on master. Also, I might wait till @MichaelHatherly gets a chance to sort out the navbar stuff because that's a bit too hairy to merge right now.

**Comment by shashi** [comment]
I'm trying to follow the instructions on setting up Documenter.jl with travis, but failing.

```
SSL error: could not verify peer
ERROR: failed process: Process(`travis login --auto`, ProcessExited(1)) [1]
 in pipeline_error(::Base.Process) at ./process.jl:612
 in run at ./process.jl:588 [inlined]
 in (::Documenter.Travis.##1#2)() at /home/shashi/.julia/v0.5/Documenter/src/Documenter.jl:461
 in cd(::Documenter.Travis.##1#2, ::String) at ./file.jl:59
 in genkeys(::String) at /home/shashi/.julia/v0.5/Documenter/src/Documenter.jl:458
```

I've tried everything mentioned here https://github.com/travis-ci/travis.rb/issues/141 but it hasn't worked.

**Comment by MichaelHatherly** [comment]
I've not come across that error before. @shashi, does `Travis.genkeys` work for a repo that you're an owner of? Could possibly also be due to an old version of `travis`, was it installed via `gem install`, or via a distro package manager?

**Comment by shashi** [comment]
It doesn't work on packages I own either... I will try a different machine today.

**Comment by tlnagy** [comment]
So my understanding is that we need to add the ssh keys in the repo's settings. I don't think either or @shashi or I have access to that. We might need to ping Daniel and give him the ssh key to add.

**Comment by Hydrotoast** [comment]
@tlnagy, tagging @dcjones. Peeking at his commit history, it is possible he may have disappeared from the internet.

**Comment by tlnagy** [comment]
This is basically ready to go, currently waiting for upstream fixes for broken Gadfly tests, see https://github.com/dcjones/Gadfly.jl/issues/890. The last remaining TODO item is an aesthetics thing that is upstream of this PR so I'm fine with this merging.

**Pull request merged**
