### PR TITLE
WIP: Document rendering process

### PR DESCRIPTION
**Pull request by darwindarak**
This documents how a `plot` invocation gets turned into a Compose scene graph.  I'm hoping this will make it easier to refactor existing code, and encourage contributions to the code base (maybe even plugin packages).

The plan is to have a "10000-foot view" of the process, then a detailed function-by-function walkthrough.  I've only started on the overview section, and there are already many simplifications.  While many default are actually computed during the rendering process, the overview assumes that all the elements are already specified.

This is still a massive work in progress.  Any corrections/suggestions are welcome and appreciated.

@dcjones, do you mind checking for correctness?  Hopefully I haven't botched it too badly.

### CODE REVIEW

**Comment by dcjones** [comment]
I pushed a couple typo fixes, but it looks great. Really useful stuff.

**Comment by timholy** [comment]
Any reason not to merge? Indeed looks useful!

**Comment by darwindarak** [comment]
There are still quite a few sections I haven't had time to add.  If it is usable as it is now, maybe we can merge it first and use it as a base for further additions.

**Comment by dcjones** [comment]
Sounds good. Feel free to add to this anytime.

**Comment by dcjones** [comment]
Looks nice: http://gadflyjl.org/dev_pipeline.html :+1:

**Pull request merged**
