### PR TITLE
Compose.Image doesn't exists right now

### PR DESCRIPTION
**Pull request by maximsch2**
Latest version fails to load on 0.4 otherwise

### CODE REVIEW

**Comment by timholy** [comment]
I'm guessing this is another one of those dependent-package (probably, Cairo) issues. @dcjones, just chew me out if I'm messing up by merging this.

**Comment by timholy** [comment]
(And, thanks @maximsch2!)

**Comment by maximsch2** [comment]
Thanks for merging it! It would be great to also tag a new version, as the latest one doesn't load now without Cairo installed.

**Comment by dcjones** [comment]
Thanks Maxim and Tim. That was one of those conditional functions. I'm not sure how I missed it. I'm tagging a new version now.

**Pull request merged**
