### PR TITLE
Get docs building and fix #678

### LINKED ISSUE #678: ERROR: `weighted_color_mean` has no method matching weighted_color_mean(::Array{Lab{Float32},1}, ::Array{Float64,1})
I tried one of the gadfly examples at juliabox.org. it does not work. 

julia> plot(x=x,y=y,color=x+y, Geom.rectbin,                                                                          
            Scale.ContinuousColorScale(Scale.lab_gradient(color("green"),                                             
                                                          color("white"),                                             
                                                          color("red"))))                                             
WARNING: color("green") is deprecated, use colorant"green" or parse(Colorant, "green")                                
 in color at /opt/julia_packages/.julia/v0.3/Colors/src/parse.jl:145                                                  
WARNING: color("white") is deprecated, use colorant"white" or parse(Colorant, "white")                                
 in color at /opt/julia_packages/.julia/v0.3/Colors/src/parse.jl:145                                                  
Error showing value of type Plot:                                                                                     
ERROR: `weighted_color_mean` has no method matching weighted_color_mean(::Array{Lab{Float32},1}, ::Array{Float64,1})
 in f at /opt/julia_packages/.julia/v0.3/Gadfly/src/color_misc.jl:76                                                  
 in apply_scale_typed! at /opt/julia_packages/.julia/v0.3/Gadfly/src/scale.jl:724                                     
 in apply_scale at /opt/julia_packages/.julia/v0.3/Gadfly/src/scale.jl:692                                            
 in apply_scales at /opt/julia_packages/.julia/v0.3/Gadfly/src/scale.jl:39                                            
 in apply_scales at /opt/julia_packages/.julia/v0.3/Gadfly/src/scale.jl:59                                            
 in render at /opt/julia_packages/.julia/v0.3/Gadfly/src/Gadfly.jl:715                                                
 in display at /opt/julia_packages/.julia/v0.3/Gadfly/src/Gadfly.jl:1026                                              
 in display at /opt/julia_packages/.julia/v0.3/Gadfly/src/Gadfly.jl:149                                               
 in print_response at REPL.jl:139                                                                                     
 in print_response at REPL.jl:124                                                                                     
 in anonymous at REPL.jl:586                                                                                          
 in run_interface at ./LineEdit.jl:1379                                                                               
 in run_frontend at ./REPL.jl:818                                                                                     
 in run_repl at ./REPL.jl:169                                                                                         
 in _start at ./client.jl:400                                                                                         
                                                                                                                      
julia> Base.versioninfo()                                                                                             
Julia Version 0.3.11                                                                                                  
Commit 483dbf5* (2015-07-27 06:18 UTC)                                                                                
Platform Info:                                                                                                        
  System: Linux (x86_64-unknown-linux-gnu)                                                                            
  CPU: Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz                                                                      
  WORD_SIZE: 64                                                                                                       
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)                                                
  LAPACK: libopenblas                                                                                                 
  LIBM: libopenlibm                                                                                                   
  LLVM: libLLVM-3.3                                                                                                   
                                                                                                                      
julia>

### PR DESCRIPTION
**Pull request by timholy**
This cleans up some residual problems with the Colors transition (sorry), and gets the docs building on my local machine.

I'm not certain whether the tests I've added went into the right places, nor whether the "broken doc examples" (see 4th commit) really were broken as examples or whether Gadfly was supposed to handle them but wasn't.

### CODE REVIEW

**Comment by timholy** [comment]
Since this fixes an open bug, I'm going to merge.

**Comment by dcjones** [comment]
Ok, thanks!

It's best to keep tests as separate files, since it evaluates these files, renders the plot on various backends and puts them in `output/tests.html` for inspection. Otherwise only the last plot is shown.

**Comment by timholy** [comment]
Not sure I understand, can you flag one of the errors for me? I will fix.

**Comment by dcjones** [comment]
I already split those up (https://github.com/dcjones/Gadfly.jl/commit/17f1d47fa29da1e894d53e48ee5e4be48d18b682). If you have a test file like:

```julia
a = plot(...)
b = plot(...)
```

`runtests.jl` will eval the file and draw the resulting plot (https://github.com/dcjones/Gadfly.jl/blob/master/test/runtests.jl#L134), but only `b` will get drawn here since it's the last expression. You can put multiple plots in one test file, but you have to stack (`vstack(a, b)`) them so they all get drawn.

**Comment by timholy** [comment]
Ah, now I get it. Thanks for explaining!

Could one just call `display` directly?

**Comment by dcjones** [comment]
It could work that way, but there would need to be a display type that writes to the output file.

**Pull request merged**
